apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-lnoy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fozy-tenant/status-quarkus-io/statusquarkusio-lnoy@sha256:b166711d99e1d75d3401883a2c6c033461d83685c8da0bd63b5505832c7d14c0
        name: my-java-quarkus
        resources: {}
status: {}
